# Generated by Django 3.2.15 on 2022-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20220920_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to='jobapp.Profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_interest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
